minimumReleaseAgeExclude:
  - '@react-pdf/font@4.0.10'
  - '@react-pdf/layout@4.7.1'
  - '@react-pdf/pdfkit@6.0.1'
  - '@react-pdf/render@4.6.1'
  - '@react-pdf/renderer@4.6.1'
  - '@react-pdf/stylesheet@6.2.3'
  - '@react-pdf/textkit@6.4.1'
  - '@react-pdf/types@2.11.3'
